services:
  - type: web
    name: ai-003-backend
    env: docker
    plan: starter # Free plan is not recommended for production
    dockerfilePath: clothing-inspection-backend/Dockerfile
    dockerContext: ./clothing-inspection-backend
    envVars:
      - fromGroup: production-env
      - key: PORT
        value: 10000
    autoDeploy: true
    healthCheckPath: /api/healthz # Should be implemented in backend

  - type: static
    name: ai-003-front
    env: static
    plan: starter # Free plan is not recommended for production
    rootDir: clothing-inspection-frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: ai-003-backend
          property: url
    routes:
      - type: rewrite
        source: "/api/*"
        destination: "https://ai-003-backend.onrender.com/api/:splat"
      - type: rewrite
        source: "/*"
        destination: "/index.html"

# Note: 1) create an Environment Group named 'production-env' in Render
#       2) populate all variables (DB_PASSWORD, JWT_SECRET, SMTP_*, etc.)
#       3) Ensure the backend service URL is correctly set for the frontend.
