services:
  - type: web
    name: backend
    env: docker
    plan: standard # Free plan is not recommended for production
    dockerfilePath: clothing-inspection-backend/Dockerfile
    dockerContext: ./clothing-inspection-backend
    envVars:
      - fromGroup: production-env
      - key: PORT
        value: 10000
    autoDeploy: true
    healthCheckPath: /api/healthz # Should be implemented in backend

  - type: static
    name: frontend
    env: static
    plan: starter # Free plan is not recommended for production
    buildCommand: cd clothing-inspection-frontend && npm ci && npm run build
    staticPublishPath: clothing-inspection-frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: backend
          property: url
    routes:
      - type: rewrite
        source: "/api/*"
        destination: "/api/:splat"
      - type: rewrite
        source: "/*"
        destination: "/index.html"

  - type: mysql
    name: db
    plan: starter-db # Free plan has limitations
    properties:
      databaseName: clothing_inspection
      user: clothing_user

# Note: 1) create an Environment Group named 'production-env' in Render
#       2) populate all variables (DB_PASSWORD, JWT_SECRET, SMTP_*, etc.)
#       3) Ensure the backend service URL is correctly set for the frontend.
